### ISSUE TITLE
Translation pt-br

### ISSUE THREAD

**Issue by hanelore** [decred/dcrandroid#117]
Hi.

What would be the best way to start the translation?

Thanks.

**Comment by denyszayets** [comment]
you need to talk to @behindtext and @raedah about this.

**Comment by hanelore** [comment]
Thanks @denyszayets.

I will wait @behindtext and @raedah instructions about it.

Thanks again :)

**Comment by hanelore** [comment]
PR sent [here](https://github.com/decred/dcrandroid/pull/367). Thanks.
