### ISSUE TITLE
Feature request: Drop down menu when sending fund to address/account within same wallet

### ISSUE THREAD

**Issue by gravityz3r0** [decred/dcrandroid#119]
Very much like the desktop counter part of the decrediton, it would be nice to have a drop down menu to select when transferring from one account to another within the same wallet. 

Ie: use address when sending to an external wallet, or selecting from a drop down menu when sending to other account within the same wallet.

**Comment by denyszayets** [comment]
Thanks for your feedback. Will add this to my list
