### ISSUE TITLE
Push notification shows incoming tx multiple times

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrandroid#122]
Seems like the push notification needs a bit of tweaking, it shows the incoming transaction multiple times:

![image](https://user-images.githubusercontent.com/16287891/45226198-8f269180-b2be-11e8-9599-d53ec79923c4.png)

Device: Moto G5
OS: Android 7.0
Bug was reproduced on the same device

**Comment by gravityz3r0** [comment]
Are you sure these dupes are multiples of a single incoming transaction? Maybe it was the old notification that wasn't cleared by you. You have to either swipe, or click on the notification to remove it.

**Comment by noahpierau** [comment]
The screenshot shows one single notification, I'm sure. I noticed this issue during the first incoming tx on my wallet (from faucet  request). After I dismissed the first notification (which looked identical) I requested a second faucet transfer to take this screenshot.

**Comment by noahpierau** [comment]
In some cases the tx is displayed 5 times, in other cases 2, 3 or 4. I've also seen the correct version (1) but so far it has varied each time I requested funds.

**Comment by C-ollins** [comment]
Fixed in https://github.com/decred/dcrandroid/commit/a881d6da436a4f22bc2a807f62e771adad4db174 @ #156

**Comment by C-ollins** [comment]
Fixed in
