### ISSUE TITLE
Improve readability of insufficient balance warning

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrandroid#123]
When I overspend my wallet, this is the warning I get. It needs to be more readable / user friendly.

For example: `Warning: insufficient balance`

![image](https://user-images.githubusercontent.com/16287891/45227740-7d92b900-b2c1-11e8-9bec-8be6e90bf4e2.png)

**Comment by denyszayets** [comment]
Thanks for your feedback. Will add this to my to do list.

**Comment by denyszayets** [comment]
![4 2 1 send insufficient balance](https://user-images.githubusercontent.com/33739891/45509724-5c6d1500-b766-11e8-9b53-833a0ca0b576.png)
