### ISSUE TITLE
Receive funds: address not fully displayed

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrandroid#128]
When I generate a new address to receive funds, the address is not fully displayed. For example, when I copy the address from the screenshot, the actual address is: [TsZRyYhxaCngERPXGKqJEX86aUHF25bemSp](https://testnet.dcrdata.org/address/TsZRyYhxaCngERPXGKqJEX86aUHF25bemSp)

My screen size is 5 inch with 1080 x 1920 pixels, 16:9 ratio.

![image](https://user-images.githubusercontent.com/16287891/45260274-dd34b580-b3e2-11e8-95c6-f159d583c4fe.png)

**Comment by noahpierau** [comment]
This is not yet fixed in version MD5: 46782290168911AD8CF97D2867499956

**Comment by C-ollins** [comment]
Can you send a screenshot of what you have and the address meant to be displayed

**Comment by noahpierau** [comment]
![screenshot_20181021-140625](https://user-images.githubusercontent.com/16287891/47266750-2bd58380-d53b-11e8-9ea5-50df7645846e.png)

It works fine with the release from 2018-10-20
Version: 18E7C5BBA2B6F62C3CF093B97059EC87
