### ISSUE TITLE
[improvement] only copy addresses from tx details screen

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrandroid#143]
When on the `Transaction details` screen, it allows me to copy addresses from the inputs/outputs. This is a nice feature to have (screenshot). However, when I paste the copied address into the address bar to send DCR, it also copied additional text with it. This even gives me a red warning, see screenshot below. It would be a good improvement to only copy the address, to make this feature more usable. 

![image](https://user-images.githubusercontent.com/16287891/45786444-c0b13c80-bc70-11e8-91f4-3b79bd2bd03f.png) 
![image](https://user-images.githubusercontent.com/16287891/45786488-e8080980-bc70-11e8-84cc-25901986b50f.png)

**Comment by C-ollins** [comment]
Resolved in #149
