### ISSUE TITLE
Balance Cutoff on Overview Screen

### ISSUE THREAD

**Issue by oregonisaac** [decred/dcrandroid#155]
The balance is cut off (as shown in the image) on the overview screen.

Test device is a Samsung Galaxy S5
![android - screen cut off](https://user-images.githubusercontent.com/4402603/46641672-aeb41280-cb27-11e8-8750-5c1f46bfcfc6.jpg)

**Comment by noahpierau** [comment]
I noticed a similar issue on my device, but for me the balance wasn't visible at all:

![image](https://user-images.githubusercontent.com/16287891/46672017-acf55800-cbd6-11e8-8f61-81efc6db2478.png)

Version MD5: 46782290168911AD8CF97D2867499956
Device: Moto G5
Screen size: 5 inch
Pixels: 1080 x 1920
Ratio: 16:9
OS: Android 7.0
