### ISSUE TITLE
Only seeing 18-20 words of seed

### ISSUE THREAD

**Issue by beatljuice** [decred/dcrandroid#164]
I only see 18 words of my seed phrase when creating a new wallet. There is no indication that I should scroll, but if I do I'm able to see 20 words total.

![image](https://user-images.githubusercontent.com/8432851/47029924-a452d380-d13a-11e8-98eb-76bb15f27ba7.png)

I'm using a Motorola Moto Z3 Play with Android version 8.1.0

**Comment by denyszayets** [comment]
Technically, we have 3 columns. Have you tried to swipe to from right-to-left? Definitely a bug.

**Comment by beatljuice** [comment]
I did try swiping left and right. Nothing happened.

**Comment by beatljuice** [comment]
I changed my display size to "small" and it now shows 3 columns and 30 words, but will not scroll at all to show the rest.

**Comment by C-ollins** [comment]
Fixed in #161
