### ISSUE TITLE
Sex up our QR codes

### ISSUE THREAD

**Issue by jzbz** [decred/dcrandroid#179]
Having a small Decred logo in the middle of the generated QR codes would be nice for branding, @linnutee do you think creating a "pixelated" Decred logo such as the example below is possible?

https://lh3.googleusercontent.com/fx44vBI7In7aaoLaA9-AV23rIRn0Dtt5DepkOVje9VJ9s5mlVx4C2aegcEPPrTKTGy4=w1920-h916

**Comment by denyszayets** [comment]
Will add this to the 2.6 revision. @linnutee thoughts?

**Comment by emmanuelkehinde** [comment]
#420 should close the issue

**Comment by C-ollins** [comment]
Closed by #420
