### ISSUE TITLE
Add send/receive buttons to main screen

### ISSUE THREAD

**Issue by jzbz** [decred/dcrandroid#181]
Right now the home screen basically only shows balance/recent transactions.
Having buttons for sending and receiving would improve UX.

Example:
https://lh3.googleusercontent.com/Mn1B7F9BuaMTUsXPoUzXl1SQX8_-mWZPY2qm8aEIek2u1YX_C-rRRwx8ZCvaI_UjrK8=w1920-h916

**Comment by raedah** [comment]
@denyszayets

**Comment by denyszayets** [comment]
We'll be addressing this in the upcoming design revision. This will include quick navigation bar at the bottom of the screen to quickly send, receive, review etc.
