### ISSUE TITLE
Multiple wallets feature

### ISSUE THREAD

**Issue by raedah** [decred/dcrandroid#188]
Here is an initial concept via @denyszayets , there are some more details that need to be flushed out on how this will function and be engineered.

![47671348-acbcfc80-db85-11e8-83db-1e6aec92b5b7](https://user-images.githubusercontent.com/15878246/47672634-6b8b1380-dbaa-11e8-897a-9cd807ca42bc.png)

**Comment by JoeGruffins** [comment]
Pull request #309 technically allows for up to three wallets.  I think options for more wallets, if added at all, should be added to the choose wallet directory feature.  But honestly, I can't see the use of this.  Just make another account in your wallet...

**Comment by C-ollins** [comment]
Implemented in #401
