### ISSUE TITLE
Startup sync for noobs

### ISSUE THREAD

**Issue by beatljuice** [decred/dcrandroid#229]
When starting up for the first time it takes a while for the sync to happen. New people to Decred might be surprised by this. Most wallets in the cryptoverse work almost instantly.

A simple help would be to say something like "Syncing may take several minutes on initial startup."

But better still would be to have a progress bar. I saw that there was one when opening the menu.

**Comment by raedah** [comment]
this is addressed by  https://github.com/decred/dcrandroid/pull/286
