### ISSUE TITLE
Remove the Seed Bypass on Mainnet Wallet Release

### ISSUE THREAD

**Issue by oregonisaac** [decred/dcrandroid#231]
Suggest long hold confirm should not bypass the seed anymore on the mainnet wallet.

Currently does not actually allow you to open a wallet...gives a "another process is using this Badger database" error.

**Comment by raedah** [comment]
Two issues here. The long hold is no longer available. The other crash was due to the user having low disk space. We could add a better disk space error. Would be opened as a new issue.
