### ISSUE TITLE
Make seed verification less painful

### ISSUE THREAD

**Issue by jzbz** [decred/dcrandroid#232]
When creating a new wallet the user is prompted to re-enter the seed they were supposed to have written down in the prior step.
Having the user type in the first few letters of each word in the seed and select it is pretty painful from a UX perspective, I have an idea that may make for a smoother process.

1. Display each word from the seed in order shuffled with 2 random words.
2. User taps the screen to pick the word that is supposed to be at position N.
3. Process is repeated 33 times with the last one being the checksum word which ensures they did not screw up.

The words can assemble at the top/bottom of the screen and give the option to go back if they screwed one up.
Advantage is that the user never has to type anything in, and the process will feel less tedious as well as ensuring that the entire seed is correct.

**Comment by jzbz** [comment]
Example:
```
Click on seed word #1:
[wrong word] [wrong word] [CORRECT word]

Click on seed word #2:
[wrong word] [CORRECT word] [wrong word]
...

Click on seed word #33:
[CORRECT word] [wrong word] [wrong word]
```

**Comment by jamiekeefer** [comment]
Not sure how this would work. Now an impossible seed to guess can be guessed in a !35 tries? How would this auto seed completion get the list of words? Granted the UX is a little clunky but I think it's supposed to require a highly manual process.

**Comment by jzbz** [comment]
@jamiekeefer This would only apply to confirming you have written down the seed correctly on initial set-up, not seed restore. The seed restore process would still require the user to input every single word (with the help of auto-complete).

**Comment by noahpierau** [comment]
>How would this auto seed completion get the list of words?

From the pgp word list: https://github.com/decred/dcrwallet/blob/master/pgpwordlist/wordlist.go

**Comment by raedah** [comment]
https://github.com/decred/dcrandroid/pull/215
