### ISSUE TITLE
Detect no network before attempting send.

### ISSUE THREAD

**Issue by raedah** [decred/dcrandroid#238]
We can detect this error before the user tries to send the transaction. Do not ask them for their sending password or try to send if ther are 0 peers connected. Just display the error "Not connected to the network."

![photo_2018-11-27_00-36-49](https://user-images.githubusercontent.com/15878246/49050716-97ff7300-f1dc-11e8-89ab-8f74c5f45cc2.jpg)

**Comment by C-ollins** [comment]
Fixed in https://github.com/decred/dcrandroid/commit/dc1006e503054a17b1170fb67fb84ec2dce65903
