### ISSUE TITLE
Replace spash screen with something more aesthetic

### ISSUE THREAD

**Issue by jzbz** [decred/dcrandroid#260]
Would be preferable to have something more polished for final release. Have already pinged @linnutee.

**Comment by linnutee** [comment]
Ok needed to get an android testing device, so just did a quick overview of the app. 

The splash screen is a least of the issues. Fundamentally the state of design is problematic and never really got any greenlight in the /dcrdesign issues (unfortunately that seemed to be completely ignored by the designer).

Consideration about releases: unlike the desktop software, these apps go out of google playstore and apple appstore. I’m on the opinion half-baked stuff should never be up there. Google play store is bit more of a chaos and mess, thus can get away with more but apple store for mobile users has an expectation of quality behind it. If someone downloads a crappy app from there, can be quite certain they will not download it again – so putting a nail in the mobile users onboarding.

In regards of the wallets UX, interaction design has some critical issues: most notably instances where user gets stuck (e.g. restore wallet) and needs to close down the app to continue, onboarding is not optimal for mobile (think of copay and several other who have set quite decent benchmarks to build upon).

The visual design is currently an odd mix of material design and copy-paste of Decrediton. I’ve told in the now closed design issue that it would be most optimal and fastest to design the wallet purely in material design and simply do a minimal DCR customization – as in color scheme, icons (within the limitations intended by material design). This has been an approach for copay as well blockchain.com wallets. Staying true to the native os, thus minimal friction. Decrediton on the other hand has been always a desktop first app design-wise. Although most views got a responsive design just about done to them and could be replicated here, I think it would be less optimal approach. 

Right now it’s neither this or that, as well there’s a number of really odd elements, e.g. inconsistent icons, the motion design (which is simply conflicting work, as @kyleFirethought has produced a huge library of quality motion assets prior to that). There’s also a number of issues regarding logical use of colors and other details I won’t dig into, as these have been covered in the dcrdesign issues feedback.

I’m aware there isn’t currently a designer on the project. As an action to take, would recommend to post a new master issue to /dcrdesign that sums up the app, scope of work and approach. I can tag this issue with help needed and it can be promoted to look for new UI/UX talent or potentially be taken on by some of the designers from block42 if their schedule allows.

Would estimate that re-designing the app in a pure material design should take no longer than 2 weeks FTE for a competent designer (e.g. experience with mobile apps/crypto/material design/ability to understand and work within an identity framework) to work with. This is considering the rich amount of examples and available assets to work with. That designer should also closely engage with the developers, by actively auditing the implementation and making any updates where needed. Quite important task as the implementation tends to bring a lot of entropy to the design, esp. when parties are working remotely as we do in the open-source environment.

**Comment by LordRichmond** [comment]
Here are the options for the loading screen - Dark and Light themes.

[Decred Loading Screen.zip](https://github.com/decred/dcrandroid/files/2745020/Decred.Loading.Screen.zip)

**Comment by LordRichmond** [comment]
![webp net-gifmaker 2](https://user-images.githubusercontent.com/46307650/51646522-2132ec00-1f79-11e9-9adb-9daffe3e9101.gif)

Here's the new splash screen animation.

**Comment by kyleFirethought** [comment]
![20190124224352](https://user-images.githubusercontent.com/7825971/51713459-e0df7680-2029-11e9-900b-778987577ae7.gif)

Preview in Google Chrome^ | This needs to be put to rest. Attn: @raedah

I have created an Android Drawable Vector file with complimentary SVG spritesheet so there are plenty of avenues for implementation to spruce up the splash.

Design- wise it follows along the same 'look' as produced for the ending credits .mogrt project requested by Justin Santoro on behalf of Raedah Group.  You can find the necessary files in the zip attached. 

[splash.zip](https://github.com/decred/dcrandroid/files/2793926/splash.zip)

If you have no issues implementing AVDs into the software then there is a whole library for relevant XML files that can be used where appropriate. 

Any future issues like this can be referenced in dcrdesign.  I hope this helps the dcrandroid effort,

Wish you all a pleasant weekend.
