### ISSUE TITLE
problems with paste functionality on Security page, device specific

### ISSUE THREAD

**Issue by raedah** [decred/dcrandroid#261]
The 3 fields on the security page for message signing are not properly supporting long hold for select all or paste. Looks to be device specific, could be being caused by an older version of android. Do not have the specific runtime information available. Should be tested on other devices.

**Comment by degeri** [comment]
I also faced the same issue on my samsung phone. 

Was about to open this issue but github caught it as a potential duplicate :)
 
Android Version 8.1.0 (Oreo)
Samsung Experience Version: 9.5
Video:
[2018_12_28.mp4.zip](https://github.com/decred/dcrandroid/files/2715357/2018_12_28.mp4.zip)
