### ISSUE TITLE
Fingerprint implementation 

### ISSUE THREAD

**Issue by MaskedMagnet99** [decred/dcrandroid#294]
Hi,

Just sending in a new request that I bought up in the telegram group earlier today. 
The new mobile wallet is an extremely impressive piece of tech. 

Working in the banking system I currently work with the public and opinions regarding the mobile tech that's used in mobile banking apps. 

I get constant feedback that a simple, clean lined app is what makes people use it. Fingerprint access is among the most requested item of importance for millions of customers to want to use it (including over 50's). I believe the QR code function will be a major selling point and ease of use case once more day to day people start spending crypto for goods in the future.
The tech is so important, but the end user just wants easy access, beautiful interface, simplicity and it to work flawlessly. DCR seems to have most of this down pat even though the current version is still such an early release.

But I would strongly suggest the possibility of adding a fingerprint for opening the app up, and password spend to simplify ease of use in terms of daily transactions out of the wallet as adoption grows.

If I were to need to use my mobile dcr wallet multiple times per day, having a fingerprint optionwould encourage me to use it.

Thanks for taking the time to read my option. 

Cheers!

Simon

**Comment by C-ollins** [comment]
Closed by #413
