### ISSUE TITLE
Addresses should copy to the clipboard on long hold

### ISSUE THREAD

**Issue by raedah** [decred/dcrandroid#3]
Transaction details page, New Wallet Output

**Comment by raedah** [comment]
The 'Your address is copied' text is appearing to the right of the screen. It should be centered, probably higher in the screen so its not covered the by the users finger, and the text can be larger. Also, you should say hash copied when its a hash, but address copied when its an address.

**Comment by raedah** [comment]
some of this was also completed in https://github.com/raedahgroup/dcrandroid/pull/38

**Comment by macsleven** [comment]
working on it

**Comment by raedah** [comment]
still seeing copied with a lower case c in latest build. Should be upper case.
