### ISSUE TITLE
Display error on failed QR scan

### ISSUE THREAD

**Issue by beatljuice** [decred/dcrandroid#303]
When scanning a QR code generated in Decrediton the scanner acts like it scanned, and returns to the Sending Decred screen, but the Destination Address field isn't filled in.

**Comment by beatljuice** [comment]
This may not be an issue. Forgot I was using testnet, trying to scan a mainnet address.

**Comment by raedah** [comment]
Probably worth it to detect the conflict and display an informative error to the user.
