### ISSUE TITLE
Disable Users from clearing app data via settings

### ISSUE THREAD

**Issue by macsleven** [decred/dcrandroid#339]
Users should not be allowed to clear app data via settings, which is a bypass of deleting wallet without providing "spending pin/password"

![image 2019-02-25 14 24 53](https://user-images.githubusercontent.com/794430/53340365-203f0280-3909-11e9-8d9e-f3aa91c24ba5.jpg)

**Comment by C-ollins** [comment]
I'd be closing this. A user can bypass that by uninstalling and reinstalling the app which is the same as clearing app data so that won't have any effect.

**Comment by macsleven** [comment]
then the delete wallet function in the app is not needed, because it requires user password to do that

**Comment by C-ollins** [comment]
I guess password shouldn't be needed to delete wallet since the app can be uninstalled

**Comment by raedah** [comment]
Entering password is a confirmation step so they dont accidentally hit the button.
