### ISSUE TITLE
Use new cointype on new wallets

### ISSUE THREAD

**Issue by raedah** [decred/dcrandroid#341]
see decrediton support for both 20 and 42 https://github.com/decred/decrediton/blob/master/app/wallet/constants.js#L30-L33

current dcrandroid derivation path is set as a constant, doesnt change. https://github.com/decred/dcrandroid/blob/master/app/src/main/java/com/dcrandroid/data/Constants.java#L87-L88

**Comment by xaur** [comment]
Add some UI bits necessary to explain everything the user needs to know about cointype and 20 vs 42. Prevent situation like when dcrwallet warns about old cointype and you have no idea what to do about it.

**Comment by raedah** [comment]
related to https://github.com/decred/dcrwallet/issues/1422

**Comment by raedah** [comment]
there is a resolution for this upstream now. unblocked.
https://github.com/decred/dcrwallet/pull/1499
