### ISSUE TITLE
Display amount in full in tx confirmation dialog

### ISSUE THREAD

**Issue by C-ollins** [decred/dcrandroid#344]
This shows when I try sending 0.0001 dcr
![Screenshot_1552342994](https://user-images.githubusercontent.com/19960200/54162134-bff5a800-4454-11e9-82f9-6ceb32a52eca.png)

**Comment by raedah** [comment]
Also looks like the password msg does not fit the dialog.

**Comment by C-ollins** [comment]
Fixed in #339
