### ISSUE TITLE
dont show receive address during wallet restore

### ISSUE THREAD

**Issue by raedah** [decred/dcrandroid#376]
Receive address should not be available in the UI until after sync has completed if the user is restoring a seed phrase. Receive address can be made available in the UI during sync if the user is syncing from a newly created seed.

**Comment by crux25** [comment]
Just to be sure, by "Receive address should not be available in the UI" you mean the receive address should not be available on the specific UI below, until after sync has completed if the user is restoring a seed phrase?

![account_activity](https://user-images.githubusercontent.com/4796738/60261314-76ca4680-98d3-11e9-8930-380a239baf75.png)

**Comment by raedah** [comment]
Yes, this is because on a restore the wallet addresses might already be in use so we dont know the next unused address until after the sync/scan is complete. For newly created wallets, its not a problem.

**Comment by C-ollins** [comment]
Fixed in #385
