### ISSUE TITLE
Missed and revoked tickets don't show correctly

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrandroid#403]
Three of my testnet tickets missed their vote and had to be revoked. However, my testnet app still showed them as "Confirmed / Live" in the overview. 

Further, once I revoked the tickets the overview didn't recognize the revoke transaction: 
![image](https://user-images.githubusercontent.com/16287891/65448551-5c9ff600-de39-11e9-8fab-d63186912c9d.png)

The history tab initially showed the same tx icons, but after loading it recognized that it was a ticket-related transaction and the Confirmed / Live ticket icon showed up: 
![image](https://user-images.githubusercontent.com/16287891/65448641-996bed00-de39-11e9-92ea-086d4ea9c8f3.png)

Not sure how much extra work it is to detect missed / revoked tickets and display the correct icons? For reference, this is how the Revoked ticket icon looks in Decrediton:
![image](https://user-images.githubusercontent.com/16287891/65448765-ddf78880-de39-11e9-8393-467a1b7814c8.png)

Since this happens very rarely it's not a pressing issue, but it's good to be aware of it.

**Comment by noahpierau** [comment]
This issue seems to be solved in the 2019-10-21 version of the testnet wallet.

**Comment by C-ollins** [comment]
Fixed in #401
