### ISSUE TITLE
Mainnet wallet transaction lookup using testnet dcrdata, not mainnet

### ISSUE THREAD

**Issue by TechyGrue** [decred/dcrandroid#425]
Was concerned for a sec until I saw the url. Looked up a transaction and saw a transaction not found message.

Build date: mainnet 2019-01-26

**Comment by TechyGrue** [comment]
This was from the app downloaded in the Google Play Store. Relevant code: TransactionDetailsDialog.kt Line 196, but I don't see anything wrong, so guessing BuildConfig have for forgotten to be switched off TESTNET somewhere for this mainnet release?

**Comment by C-ollins** [comment]
The mistake exists only on the Play Store version, it has been fixed on master.
