### ISSUE TITLE
Add statistics page

### ISSUE THREAD

**Issue by C-ollins** [decred/dcrandroid#432]
There's a "View statistics" option under Debug in Settings that do nothing when clicked, it should lead to a statistic page similar to this screenshot gotten from the app design mockup;
<img src="https://user-images.githubusercontent.com/19960200/76165719-8172f600-6159-11ea-85d5-029184a28f81.png" height="500">

Related to #221

**Comment by raedah** [comment]
Also see https://github.com/decred/dcrandroid/pull/397
