### ISSUE TITLE
Fix UI freezing while syncing - proposals how to fix

### ISSUE THREAD

**Issue by svitekpavel** [decred/dcrandroid#474]
Device: Samsung Galaxy S10

**Problem (already known)**
* UI is blocked while syncing is in progress
* HW volume down button took 30 seconds to actually turn the volume down
* Unlocking the phone took 5-6 seconds as well

**This all points to one issue**
The syncing actually happens in the main (UI) thread.

**Current code**
I am a software dev, but I'm not coding on mobile. I talked to 2 mobile developers (1 Android and 1 iOS dev), both point to conclusion that main (UI) thread is blocked by the syncing service.

I looked at the code, this is where it's called:
https://github.com/decred/dcrandroid/blob/master/app/src/main/java/com/dcrandroid/HomeActivity.kt#L313

**Solution 1**
I am reading about Processes in Android and I found this:
https://developer.android.com/guide/components/broadcasts#effects-process-state

In the code you execute following: `sendBroadcast(Intent(Constants.SYNCED))`

You can see in the link also implementation of `AsyncTask` interface, which was also recommended by the Android of the developers.

I found this tutorial on Upwork blog how to use it

https://www.upwork.com/hiring/mobile/why-you-should-use-asynctask-in-android-development/

**Solution 2**

The Android developer suggested other solutions as well:
_Also I could mention alternatives for running code on background thread would be RxJava(https://github.com/ReactiveX/RxJava) and Kotlin Coroutines (https://github.com/Kotlin/kotlinx.coroutines)_

_These tools are much more powerful and much more popular in Android, but it’s much harder to use them properly_

**Solution 3 (least refactoring needed?)**
From the Android developer:
_I have one more idea how you can deal with that issue. This one I think requires the least amount of refactoring. Just use IntentService instead of a Service_ 

https://developer.android.com/reference/android/app/IntentService

**The only issue is that this approach will be deprecated on Android 11 and above.**

--

Unfortunately, he doesn't code in Go and so, he can't create a working PR.

Let me know if this helps!

**Comment by svitekpavel** [comment]
![Screenshot_20200522-191351_Decred Wallet Testnet](https://user-images.githubusercontent.com/988706/82698212-aeb84600-9c6a-11ea-8563-a5ec33110b39.jpg)

**Comment by svitekpavel** [comment]
As you can see on the screenshot above, on my Samsung S10 the app is being suspended and then killed by the system. This also indicates that the main thread is not responding which seems to conclude that the syncing is indeed in the main application thread.

**Comment by C-ollins** [comment]
Lag during sync was fixed here https://github.com/raedahgroup/dcrlibwallet/pull/134

**Comment by svitekpavel** [comment]
> Lag during sync was fixed here [raedahgroup/dcrlibwallet#134](https://github.com/raedahgroup/dcrlibwallet/pull/134)

@C-ollins is that already included in `testnet 2020-05-05` release?

**Comment by svitekpavel** [comment]
I am running `testnet 2020-05-05` and the UI blocking is still very bad.

**Comment by C-ollins** [comment]
No, you can test from master, or I can make you a testnet build.

**Comment by svitekpavel** [comment]
I am happy to test a new build which will be published to store.

**Comment by C-ollins** [comment]
I'll make a comment here when it gets published.

**Comment by C-ollins** [comment]
Testnet update has been uploaded.

**Comment by svitekpavel** [comment]
Thank you @C-ollins 

I downloaded the build from yesterday - 17th May and I confirm that the UI is not freezing anymore on my Samsung S10. 

I also reinstalled the application and the UI also works good during the initial sync.

Good job 👍
