### ISSUE TITLE
Android App Design

### ISSUE THREAD

**Issue by denyszayets** [decred/dcrandroid#80]
Android App Design

[Prototype](https://xd.adobe.com/view/336d6bf4-d220-4388-a795-4012bab46cee/)
[Design Specs](https://xd.adobe.com/spec/66df1bf8-1112-4c15-ab6e-0c6fe71318f4/)

@raedah @macsleven 

## 0.0 Loading Screen
![0 loading screen](https://user-images.githubusercontent.com/33739891/39526836-02470b6c-4dee-11e8-96de-0fc74f1da13e.png)

## 1.0 Start
![1 start](https://user-images.githubusercontent.com/33739891/39526849-082dc14c-4dee-11e8-80da-46b94d726cef.png)

## 2.0 New Wallet
![2 0 new wallet](https://user-images.githubusercontent.com/33739891/39526851-0a186c50-4dee-11e8-9ef1-362606819245.png)

## 2.1 New Wallet (confirm)
![2 1 new wallet confirm](https://user-images.githubusercontent.com/33739891/39526874-15e0f6c4-4dee-11e8-8cea-c7d64c2f3ddc.png)

## 2.2 New Wallet (2nd confirm) 
![2 2 new wallet - please confirm by typing](https://user-images.githubusercontent.com/33739891/39526879-18ea79e4-4dee-11e8-8123-212ff5e59aaa.png)

## 2.3 Starting New Wallet
![2 3 starting new wallet](https://user-images.githubusercontent.com/33739891/39526895-220dff82-4dee-11e8-8154-846e928e8cd4.png)

## 3.0 Recover Wallet
![3 0 recover wallet](https://user-images.githubusercontent.com/33739891/39526903-250c5c88-4dee-11e8-902d-ddb195391209.png)

## 3.1 Recovering Animation
![3 1 recovering animation](https://user-images.githubusercontent.com/33739891/39526912-28a57d84-4dee-11e8-82c1-9d3c8129706d.png)

## 4.0 Overview Home
![4 0 overview home](https://user-images.githubusercontent.com/33739891/39526921-2d695b6a-4dee-11e8-874c-1f4282e876f6.png)

## 4.0.1 Menu
![4 0 1 menu](https://user-images.githubusercontent.com/33739891/39526941-3bdb694a-4dee-11e8-8830-7e866e5d2ed8.png)

## 4.1 Accounts
![4 1 accounts](https://user-images.githubusercontent.com/33739891/39526946-3f2d93a2-4dee-11e8-8676-b696e11022b0.png)

## 4.1.1 Account Details
![4 1 1 account details](https://user-images.githubusercontent.com/33739891/39526951-42d3e150-4dee-11e8-8391-7caa56f3b2a3.png)

## 4.1.2 Alternative Account Details
![4 1 2 alternative account details](https://user-images.githubusercontent.com/33739891/39526957-45ec6ed4-4dee-11e8-9be4-cc799cd8ef1a.png)

## 4.2 Send (default)
![4 2 send empty](https://user-images.githubusercontent.com/33739891/39526965-48826f54-4dee-11e8-9013-b3d02759c543.png)

## 4.2.1 Send (filled)
![4 2 1 send filled](https://user-images.githubusercontent.com/33739891/39526970-4bb4823e-4dee-11e8-8075-f9f7620fdfdf.png)

## 4.2.2 Send (filled, send pressed)
![4 2 2 send filled send pressed](https://user-images.githubusercontent.com/33739891/39526979-4f5a02e2-4dee-11e8-8efa-6a1556277242.png)

## 4.2.3 Send Completed
![4 2 3 send completed](https://user-images.githubusercontent.com/33739891/39526985-5288b058-4dee-11e8-9d8c-cf241382e74a.png)

## 4.3 Receive
![4 3 receive](https://user-images.githubusercontent.com/33739891/39526992-56653f48-4dee-11e8-8143-4faefbdfec85.png)

## 4.4 History
![4 4 history](https://user-images.githubusercontent.com/33739891/39526993-59c50330-4dee-11e8-89ec-89021f2bda77.png)

## 4.4.0 History Filters
![4 4 0 history filters](https://user-images.githubusercontent.com/33739891/39527004-5edb31f0-4dee-11e8-9228-6e3cfc225ac4.png)

## 4.4.1 Transaction Details
![4 4 1 transaction details](https://user-images.githubusercontent.com/33739891/39527009-61ffc634-4dee-11e8-902b-5ab164436ea5.png)

## 4.4.2 Transaction Full Details
![4 4 2 transaction full details](https://user-images.githubusercontent.com/33739891/39527017-648097a8-4dee-11e8-8fce-d2046d3bc716.png)

## 4.5 Settings
![4 5 settings](https://user-images.githubusercontent.com/33739891/39527022-669095a2-4dee-11e8-9c15-198fc42b1c8f.png)

## 4.6 Help
![4 6 help](https://user-images.githubusercontent.com/33739891/39527029-6b945d9a-4dee-11e8-8473-341fc1f253a0.png)

## 5.0. Chain Connected
![5 0 chain connected](https://user-images.githubusercontent.com/33739891/39527050-7929ed80-4dee-11e8-8feb-91c1a8998d90.png)

## 5.1 Fetching Headers
![5 1 fetching headers](https://user-images.githubusercontent.com/33739891/39527061-81ce29ba-4dee-11e8-9c6f-723958669900.png)

## 5.2 Rescanning Chain
![5 2 rescanning chain](https://user-images.githubusercontent.com/33739891/39527107-a343aaa2-4dee-11e8-803b-c3241c31207b.png)

## 6.0 History Alternative
![6 0 history alternative](https://user-images.githubusercontent.com/33739891/39527088-92bf3af2-4dee-11e8-93f1-0d644e2423ce.png)

## 6.1 History with filters (alternative)
![6 1 history old with filter](https://user-images.githubusercontent.com/33739891/39527089-92cf5766-4dee-11e8-9020-a5b44b293007.png)

**Comment by denyszayets** [comment]
I'll be making small changes to 4.0.1 Menu. We'll use the same icons we have in decrediton.

**Comment by denyszayets** [comment]
Working on a revised design for this application.

**Comment by codegreenie** [comment]
Creating this app using Framework7 
https://github.com/codegreenie/decredandroidwallet

https://build.phonegap.com/apps/3227459/download/android/?qr_key=ha6U8Zkw7M1rFs6Jw2HB

**Comment by denyszayets** [comment]
Revision 2.0 of this design has been sent for review.
https://xd.adobe.com/spec/75bfaef5-157c-4d53-6fb2-2a5e989edb7d-038e
Keeping you all in the loop guys. Thanks for the hard work on this implementation!
